version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_cadastro
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: cadastro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend       # constrói a imagem localmente
    container_name: fastapi_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "1234"
      DB_NAME: cadastro

  frontend:
    build: ./frontend      # constrói a imagem localmente
    container_name: html_front
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
