apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  
  schedule: "15 19 * * *"   # todo dia às 02:00
  timeZone: "America/Sao_Paulo"
  concurrencyPolicy: Forbid  # não permitem execuções simutaneas 
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1 # quantos pods ele cria quando um pod falhar
      template:
        spec:
          restartPolicy: OnFailure # ele tenta mesmo em casa de falhas externas como rede essas coisas 
          containers:
          - name: backup
            image: mysql:8.0
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            command:
              - sh
              - -c
              - |
                echo "Iniciando backup..."
                mysqldump -h mysql -u$DB_USER -p$DB_PASSWORD \
                  --all-databases \
                  > /backup/mysql-$(date +%F).sql
                echo "Backup finalizado"
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mysql-backup-pvc
